//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.ExpertFinder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.ExpertFinder.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (300 characters max).
        /// </summary>
        public static string AboutMePlaceHolderText {
            get {
                return ResourceManager.GetString("AboutMePlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutMeTitle {
            get {
                return ResourceManager.GetString("AboutMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string BotCommandLogout {
            get {
                return ResourceManager.GetString("BotCommandLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string BotCommandMyProfile {
            get {
                return ResourceManager.GetString("BotCommandMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BotCommandSearch {
            get {
                return ResourceManager.GetString("BotCommandSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a chat.
        /// </summary>
        public static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a keyword to find people with that information in their profile..
        /// </summary>
        public static string DefaultCardContentME {
            get {
                return ResourceManager.GetString("DefaultCardContentME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update your profile so your colleagues know what you do..
        /// </summary>
        public static string EmptyProfileCardContent {
            get {
                return ResourceManager.GetString("EmptyProfileCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I couldn’t update your profile. Try again in a few minutes..
        /// </summary>
        public static string FailedToUpdateProfile {
            get {
                return ResourceManager.GetString("FailedToUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, seems like you don&apos;t have permission to access this page..
        /// </summary>
        public static string ForbiddenErrorMessage {
            get {
                return ResourceManager.GetString("ForbiddenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullNameTitle {
            get {
                return ResourceManager.GetString("FullNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists..
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to profile.
        /// </summary>
        public static string GotoProfileTitle {
            get {
                return ResourceManager.GetString("GotoProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can help you find people in your organization with specific expertise and skills. Here’s what you can do:.
        /// </summary>
        public static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Type a skill (like “data visualization”), interest (“hiking”), or the name of a school to find people with that information in their profile..
        /// </summary>
        public static string InitialSearchResultMessageBodyText {
            get {
                return ResourceManager.GetString("InitialSearchResultMessageBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are list of things one can do:.
        /// </summary>
        public static string InitialSearchResultMessageHeaderText {
            get {
                return ResourceManager.GetString("InitialSearchResultMessageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (100 characters max).
        /// </summary>
        public static string InterestsPlaceHolderText {
            get {
                return ResourceManager.GetString("InterestsPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        public static string InterestTitle {
            get {
                return ResourceManager.GetString("InterestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You don&apos;t seem to be a user in the organization for which I was set up..
        /// </summary>
        public static string InvalidTenant {
            get {
                return ResourceManager.GetString("InvalidTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is successful!.
        /// </summary>
        public static string LoginSuccessText {
            get {
                return ResourceManager.GetString("LoginSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select up to 5 user profiles..
        /// </summary>
        public static string MaxUserProfilesError {
            get {
                return ResourceManager.GetString("MaxUserProfilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfileTitle {
            get {
                return ResourceManager.GetString("MyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how your profile looks to others. Update your profile with skills, interests, and schools..
        /// </summary>
        public static string MyProfileWelcomeCardContent {
            get {
                return ResourceManager.GetString("MyProfileWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To search for experts, you’ll need to sign in..
        /// </summary>
        public static string NotLoggedInText {
            get {
                return ResourceManager.GetString("NotLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshLinkText {
            get {
                return ResourceManager.GetString("RefreshLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (200 characters max).
        /// </summary>
        public static string SchoolsPlaceHolderText {
            get {
                return ResourceManager.GetString("SchoolsPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string SchoolsTitle {
            get {
                return ResourceManager.GetString("SchoolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click **Search** to filter for individuals by skills, interests, and other attributes in their profiles..
        /// </summary>
        public static string SearchCardContent {
            get {
                return ResourceManager.GetString("SearchCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found. Try a different keyword..
        /// </summary>
        public static string SearchResultNoItemsText {
            get {
                return ResourceManager.GetString("SearchResultNoItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for experts.
        /// </summary>
        public static string SearchTaskModuleTitle {
            get {
                return ResourceManager.GetString("SearchTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a term to search for.
        /// </summary>
        public static string SearchTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("SearchTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for individuals by skills, interests, and other attributes in their profiles..
        /// </summary>
        public static string SearchWelcomeCardContent {
            get {
                return ResourceManager.GetString("SearchWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To search for experts, you’ll need to sign in..
        /// </summary>
        public static string SignInCardText {
            get {
                return ResourceManager.GetString("SignInCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out..
        /// </summary>
        public static string SignOutText {
            get {
                return ResourceManager.GetString("SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information (100 characters max).
        /// </summary>
        public static string SkillsPlaceHolderText {
            get {
                return ResourceManager.GetString("SkillsPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SkillsTitle {
            get {
                return ResourceManager.GetString("SkillsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while trying to access this service..
        /// </summary>
        public static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use semicolons between each item in the fields below..
        /// </summary>
        public static string ValidationTaskModuleMessage {
            get {
                return ResourceManager.GetString("ValidationTaskModuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewButtonText {
            get {
                return ResourceManager.GetString("ViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can help you find people in your organization with specific expertise and skills. If it’s in their profile, I can find it! Here’s what you can do:.
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
